### ISSUE TITLE
`remainingTime` not updating

### ISSUE THREAD

**Issue by yasircodingcrafts** [awgv/use-timer-hook#8]

**Comment by awgv** [comment]
Hey,

[I can’t reproduce](https://codesandbox.io/s/awgv-use-timer-hook-gh-8-m1tgdf?file=/src/App.js). I’ll need more information to address this—it would be best to set up a reproducible example for me to look at, but a code snippet with your use-case might be okay too.

**Comment by awgv** [comment]
Closing this for now—feel free to comment when you have more information to share.
